# Generated by Django 4.1.7 on 2023-02-21 00:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField()),
                ('lifts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_of_order', models.BooleanField(default=False)),
                ('door', models.BooleanField(default=False)),
                ('current_floor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevators.lift')),
            ],
        ),
    ]
