# Generated by Django 4.1.7 on 2023-02-21 22:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField()),
                ('lifts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('out_of_order', models.BooleanField(default=False)),
                ('door', models.BooleanField(default=False)),
                ('current_floor', models.IntegerField(default=0)),
                ('destinations', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
            ],
        ),
    ]
